# Generated by Django 5.1.1 on 2024-09-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employer_options_alter_employer_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
