# Generated by Django 5.1.1 on 2024-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_city_alter_user_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='generated_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
