# Generated by Django 5.1.1 on 2024-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_jobtitle_generated_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
