# Generated by Django 5.1.1 on 2024-09-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_jobapplication_is_approved_jobapplication_is_pending_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtitle',
            old_name='generated_url',
            new_name='generated_form_url',
        ),
    ]
