# Generated by Django 5.1.1 on 2024-09-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_generated_url_jobtitle_generated_form_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='deadline',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='requirements',
            field=models.TextField(default=222222),
            preserve_default=False,
        ),
    ]
