# Generated by Django 5.1.1 on 2024-09-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_jobtitle_deadline_jobtitle_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtitle',
            old_name='requirements',
            new_name='requirement',
        ),
    ]
