# Generated by Django 5.1.1 on 2024-09-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_requirements_jobtitle_requirement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtitle',
            old_name='generated_form_url',
            new_name='apply_form_url',
        ),
    ]
